version: "3"
services:
  sqs:
    image: s12v/elasticmq:latest
    ports:
      - "9324:9324"

  dynamo:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"

  # serverless:
  #   build: .
  #   ports:
  #     - "3000:3000"